### PR TITLE
Make minor code tweaks to conform to lintr suggestions

### PR DESCRIPTION
**Pull request by pkq**
As with the doc suggestions, take or leave this as you wish. My primary motivation was to practice using `lintr`, so I went ahead and made the changes that seemed reasonable (e.g., removing spaces at the end of lines, reformatting for line length requirements, and using lower-case variable names). I hope this is useful, but no worries if not!

### CODE REVIEW

**Comment by jonocarroll** [comment]
Thank you. These look good. I'll have a more careful examination of them all and start a review. 

Breaking & fixing things is a great way to learn, so good on you. There's a good chance that a lot of this can be properly refactored if you're looking for more experience.

**Comment by pkq** [comment]
Thanks for the kind words. Let me know if there are other changes you'd like me to make.

**Comment by pkq** [comment]
Thanks! Any idea why this is failing on travis (ci is on my long list of things to learn)?

**Comment by jonocarroll** [comment]
There were a bunch of other issues that I also fixed. Should be green-lighting now.

CI is definitely worth learning. It's also a nightmare to get working sometimes.

**Comment by pkq** [comment]
Yup! One of these days..

**Pull request merged**
